### PR TITLE
Re-added assetable on attachments

### PR DESCRIPTION
**Pull request by Moonlight-Angel**
Basically a revert of https://github.com/galetahub/ckeditor/commit/4992843a997ba4d1062a26145af2bcd3e1b96238 since I didn't quite understand why it was removed in the first place and I think it can still be useful to a lot of people.

### CODE REVIEW

**Comment by dbourguignon** [comment]
I don't understand the remove of assessable either.
It's a breaking change

I will try your fork for now

@galetahub any backstory for this? I'd like to understand

**Comment by botularius** [comment]
I also don't understand the remove of assetable. As I did not see this pull request before I opended an issue here: 
https://github.com/galetahub/ckeditor/issues/788

**Comment by januszm** [comment]
Per @galetahub  comment: https://github.com/galetahub/ckeditor/pull/683#issuecomment-258097526

It looks like idea was to adapt CKeditor to the change in Rails where `belongs_to` is required by default, but that's wasn't ideal becase the feature, instead of being adapted to be 'optional' was simply removed.

**Comment by januszm** [comment]
But just to be fair, perhaps this feature was used so rarely and can potentially be implemented outside the scope of this gem that it was better to remove it. In all my projects, I realized, I haven't used it so it's not really a breaking change for me.

**Pull request closed without merging**
